name: Deploy MultiDocker
on:
    push:
        branches:
            - master # check your repo, your default branch might be master!

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t ovidiuradoi/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true ovidiuradoi/react-test npm test

            - run: docker build -t ovidiuradoi/multi-client ./client
            - run: docker build -t ovidiuradoi/multi-nginx ./nginx
            - run: docker build -t ovidiuradoi/multi-server ./server
            - run: docker build -t ovidiuradoi/multi-worker ./worker

            - run: docker push ovidiuradoi/multi-client
            - run: docker push ovidiuradoi/multi-nginx
            - run: docker push ovidiuradoi/multi-server
            - run: docker push ovidiuradoi/multi-worker
